In [14]:
import numpy as np


In [18]:
a = np.array([[[1,2,3] ,[21,32,36]] , [[98,32,55] , [66,4,33]]])
print(a)
a.ndim

[[[ 1  2  3]
  [21 32 36]]

 [[98 32 55]
  [66  4 33]]]


3

In [16]:
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [17]:
np.linspace(50,500,91)

array([ 50.,  55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.,
       105., 110., 115., 120., 125., 130., 135., 140., 145., 150., 155.,
       160., 165., 170., 175., 180., 185., 190., 195., 200., 205., 210.,
       215., 220., 225., 230., 235., 240., 245., 250., 255., 260., 265.,
       270., 275., 280., 285., 290., 295., 300., 305., 310., 315., 320.,
       325., 330., 335., 340., 345., 350., 355., 360., 365., 370., 375.,
       380., 385., 390., 395., 400., 405., 410., 415., 420., 425., 430.,
       435., 440., 445., 450., 455., 460., 465., 470., 475., 480., 485.,
       490., 495., 500.])

In [22]:
np.logspace(2,5, 8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [34]:
b = np.arange(0,9).reshape(3,3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
np.zeros((6,6) , dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [37]:
np.ones((4,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.eye(8 , dtype = "int")

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
?????? 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0)

In [42]:
np.random.random(6)

array([0.18904089, 0.55716378, 0.84203114, 0.32023541, 0.20953398,
       0.32734408])

In [46]:
x = np.random.randint(50,100,[5,2])
x


array([[69, 88],
       [72, 78],
       [78, 79],
       [53, 91],
       [86, 84]])

In [47]:
x.shape

(5, 2)

In [55]:

np.random.randint(100,1000, (2,5,5))

array([[[744, 678, 941, 490, 323],
        [659, 400, 205, 821, 964],
        [695, 552, 854, 276, 377],
        [121, 351, 522, 516, 298],
        [857, 759, 104, 685, 240]],

       [[664, 449, 165, 179, 898],
        [345, 262, 720, 868, 549],
        [941, 388, 884, 422, 720],
        [269, 749, 225, 100, 671],
        [102, 562, 153, 897, 103]]])

In [58]:
c = np.random.randint(0,101,10)
c

array([49, 50, 11, 95, 26,  3, 99, 41, 99, 92])

In [59]:
c.max()

99

In [60]:
c.min()

3

In [63]:
d = np.random.randint(300,501, (2,2,5))
d

array([[[483, 467, 359, 315, 451],
        [379, 375, 333, 425, 356]],

       [[454, 333, 409, 351, 465],
        [304, 448, 316, 420, 447]]])

In [64]:
d.max()

483

In [65]:
d.min()

304

In [66]:
arr = np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [68]:
arr[20:36]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [70]:
arr[20:36] = 500
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])